### ISSUE TITLE
Добавить возможность задавать параметры приложения

### ISSUE THREAD

**Issue by Qmannn** [Qmannn/food-service#27]
Необходимо добавить работу с json конфигурацией. Ниже пример работы  этой штукой

        private IConfiguration GetServiceConfiguration()
        {
            string env = Environment.GetEnvironmentVariable( "ASPNETCORE_RUNTIME_ENVIRONMENT" );
            IConfigurationBuilder configurationBuilder = new ConfigurationBuilder()
                .AddJsonFile( "appsettings.json", false ); // Базовая конфигурация

            string additioonalCofigFile = $"appsettings.{env}.json";
            if ( File.Exists( additioonalCofigFile ) )
            {
                configurationBuilder.AddJsonFile( additioonalCofigFile, false ); // Переопределения для окружения
            }

            return configurationBuilder.Build();
        }

Добавить функционал нужно в проект FoodService.

Необходимо добавить так же файлы config.json и config.dev.json
Где описать пока DbContextConfiguration (Это класс, в котором есть единственное поле ConnectionString)

В json выглядит как:

`appsettings.json`
`  {`
  `   "DbConnection": {`
     `  "ConnectionString": "Data Source=..."`
`  }`
`}`

В классе свойство называется ConnectionString так же как в json. Фактически получение экземпляра класса конфигурации происходит путем Десериализации строки в объект класса конфигурации.

Получение экземпляра выглядит так 
`public EfDbContextConfiguration EfDbContextConfiguration => _serviceConfiguration.GetSection( "DbConnection" ).Get<EfDbContextConfiguration>();`

`_serviceConfiguration `- это то, что вернул метод `GetServiceConfiguration()` показанный в примере выше

**Comment by Qmannn** [comment]
Для работы функционала необходимо установить nuget пакеты 
Microsoft.Extensions.Configuration.Json 
Автоматически так же установятся куча зависимостей этого пакета. Установить нужно только в проект FoodService

**Comment by SherlockD** [comment]
Я не очень понимаю что нужно сделать. Нужно создать класс DbContextConfiguration и написать десирелизатор для файлов конфигурации config.json и config.dev.json в которых содержится лишь поле ConnectionString?

**Comment by Qmannn** [comment]
Тебе нужно добавить функционал работы с файлами конфигурации для приложения.
Это делается с помощью `ConfigurationBuilder`.
Тут есть некоторая информация: https://metanit.com/sharp/aspnet5/2.16.php
Все работы в проекте FoodService
1) Добавляешь в корень проекта файл appsettings.json
2) Добавляешь в проект папку Config
3) Добавляешь туда класс DbContextConfiguration, туда добавляешь свойство `public string ConnectionString {get; set;}`
4) В файле appsettings.json описываешь объект конфигурации приложения.
Пример на картинке: http://joxi.ru/eAOMywdhxj596m
Там 1 - это уровень приложения - в этом json описываются все данные конфигурации приложения
2 - секция конфигурации - название лучше писать такое, как называется класс конфигурации (у тебя 'DbContextConfiguration', на скрине название 'DbConnection')
3 - Уроень секции, там описываются поля и устанавливаются значения для полей класса конфигурации. В примере на скрине класс конфигурации содержит 2 свойства 
`public string ConnectionString { get; set; }` и 
`public bool EnableQueryLog { get; set; }` Вот так выглядит http://joxi.ru/VrwnjkdiOYP4VA

5) Нужно в момент старта приложения выполнить построение объекта конфигурации.
Для этого:
5.1) Добавить в созданной папке Config класс ApplicationConfig c  методом GetServiceConfiguration, описанный в комментарии выше (самый первый коммент в issue)
5,2) Вызвать этот метод и получить экземпляр `IConfiguration`

6) Нужно получить экземпляр класса `DbContextConfiguration` из `IConfiguration`
6.1) нужно у полученного в пунке 5.2 экземпляра `IConfiguration` вызвать метод `GetSection( "тут название секции в appsettings.json.У тебя будет DbContextConfiguration" )` 
6.2) Затем у результата метода GetSection вызвать метод `Get<DbContextConfiguration>()` который уже вернет экземпляр класс DbContextConfiguration
На скрине небольшой пример
http://joxi.ru/5mdoRDqhkVyqKr
На скрине: 
1 - экземпляр полученный методом GetServiceConfiguration,
2 - Название секции в файле appsettings.json
3 - название класса, который описан в appsettings.json в указанной секции П.2


Это функционал фактически считывает информацию из файла по описанным правилам.

Для того, чтобы файл appsettings.json был доступен при запуске приложения - его нужно копировать в выходную директорию. Для этого надо сделать вот:  http://joxi.ru/5mdoRDqhkVy1Dr
